  version: '3.8'


  services:
    backend:
    image: backendjava:1
    ports:
      - target: 8083
        published: 8083
        protocol: tcp
        mode: host
    networks:
      - desarrollo_net
    db3:
      image: postgres:15.0-bullseye
      environment:
      - TZ=America/Guayaquil
      - POSTGRES_DB=integrador
      - POSTGRES_PASSWORD=anthony
      - POSTGRES_USER=postgres
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - integrador3:/var/lib/postgresql/data/pgdata
    networks:
      - desarrollo_net
    volumes:
     integrador3:
      external: true

    networks:
      desarrollo_net:
      external: true

    secrets:
      db_dev_pass:
      external: true 
